CREATE TABLE [dbo].[tbl_Team_Level]
(
	[Team_Level_Id] INT IDENTITY(1,1) NOT NULL, 	
	[Parent_Token_No] NVARCHAR(MAX) NOT NULL,
	[Child_Token_No] VARCHAR(MAX)  NULL,
	[Level] int NULL,

	[Created_On] DATETIME NOT NULL DEFAULT(GETDATE()),
	[Created_By] INT NOT NULL,
	[Created_IP] NVARCHAR(MAX) NULL,
	[Modified_On] DATETIME NULL DEFAULT(NULL),
	[Modified_By] INT NULL DEFAULT(NULL),
	[Modified_IP] NVARCHAR(MAX) NULL,
	[Is_Active] BIT NOT NULL DEFAULT(1)

 CONSTRAINT [PK_tbl_Team_Level] PRIMARY KEY CLUSTERED ([Team_Level_Id] ASC)
 WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]