namespace Common
{
    public class HttpCookiesVarConstant
    {
        public static string HTTP_COOKIES_LOGGED_USER_ID = "HTTP_COOKIES_LOGGED_USER_ID";
        public static string HTTP_COOKIES_LOGGED_TOKEN_ID = "HTTP_COOKIES_LOGGED_TOKEN_ID";
        public static string HTTP_COOKIES_LOGGED_USER_NAME = "HTTP_COOKIES_LOGGED_USER_NAME";
        public static string HTTP_COOKIES_LOGGED_EMAIL_ID = "HTTP_COOKIES_LOGGED_EMAIL_ID";
        public static string HTTP_COOKIES_LOGGED_USER_ROLE_ID = "HTTP_COOKIES_LOGGED_USER_ROLE_ID";
        public static string HTTP_COOKIES_LOGGED_USER_ROLE_NAME = "HTTP_COOKIES_LOGGED_USER_ROLE_NAME";
        public static string HTTP_COOKIES_LOGGED_PROFILE_ID = "HTTP_COOKIES_LOGGED_PROFILE_ID";
        public static string HTTP_COOKIES_LOGGED_TPA_PROFILE_ID = "HTTP_COOKIES_LOGGED_TPA_PROFILE_ID";
        public static string HTTP_COOKIES_LOGGED_TPA_USER_ID = "HTTP_COOKIES_LOGGED_TPA_USER_ID";
        public static string HTTP_COOKIES_SESSION_HEX_ID = "HTTP_COOKIES_SESSION_HEX_ID";
        public static string HTTP_COOKIES_SESSION_TRANSFER_ID = "HTTP_COOKIES_SESSION_TRANSFER_ID";

        public static string HTTP_COOKIES_LOGGED_CANDIDATE_USER_ID = "HTTP_COOKIES_LOGGED_CANDIDATE_USER_ID";
        public static string HTTP_COOKIES_LOGGED_CANDIDATE_USER_NAME = "HTTP_COOKIES_LOGGED_CANDIDATE_USER_NAME";
        public static string HTTP_COOKIES_LOGGED_CANDIDATE_EMAIL_ID = "HTTP_COOKIES_LOGGED_CANDIDATE_EMAIL_ID";
        public static string HTTP_COOKIES_LOGGED_CANDIDATE_USER_ROLE_ID = "HTTP_COOKIES_LOGGED_CANDIDATE_USER_ROLE_ID";
        public static string HTTP_COOKIES_LOGGED_CANDIDATE_USER_ROLE_NAME = "HTTP_COOKIES_LOGGED_CANDIDATE_USER_ROLE_NAME";
        public static string HTTP_COOKIES_LOGGED_CANDIDATE_PROFILE_ID = "HTTP_COOKIES_LOGGED_CANDIDATE_PROFILE_ID";

        public static string HTTP_COOKIES_EMAIL_OTP = "HTTP_COOKIES_EMAIL_OTP";
        public static string HTTP_COOKIES_MOBILE_OTP = "HTTP_COOKIES_MOBILE_OTP";

        public static string HTTP_COOKIES_DATETIME = "HTTP_COOKIES_DATETIME";

    }
}
